//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTSpecDB.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_1 {
            get {
                return ((int)(this["Multi_Copy_ID_1"]));
            }
            set {
                this["Multi_Copy_ID_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_2 {
            get {
                return ((int)(this["Multi_Copy_ID_2"]));
            }
            set {
                this["Multi_Copy_ID_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_3 {
            get {
                return ((int)(this["Multi_Copy_ID_3"]));
            }
            set {
                this["Multi_Copy_ID_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_4 {
            get {
                return ((int)(this["Multi_Copy_ID_4"]));
            }
            set {
                this["Multi_Copy_ID_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_5 {
            get {
                return ((int)(this["Multi_Copy_ID_5"]));
            }
            set {
                this["Multi_Copy_ID_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_6 {
            get {
                return ((int)(this["Multi_Copy_ID_6"]));
            }
            set {
                this["Multi_Copy_ID_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_7 {
            get {
                return ((int)(this["Multi_Copy_ID_7"]));
            }
            set {
                this["Multi_Copy_ID_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_8 {
            get {
                return ((int)(this["Multi_Copy_ID_8"]));
            }
            set {
                this["Multi_Copy_ID_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_9 {
            get {
                return ((int)(this["Multi_Copy_ID_9"]));
            }
            set {
                this["Multi_Copy_ID_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_10 {
            get {
                return ((int)(this["Multi_Copy_ID_10"]));
            }
            set {
                this["Multi_Copy_ID_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_11 {
            get {
                return ((int)(this["Multi_Copy_ID_11"]));
            }
            set {
                this["Multi_Copy_ID_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_12 {
            get {
                return ((int)(this["Multi_Copy_ID_12"]));
            }
            set {
                this["Multi_Copy_ID_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_13 {
            get {
                return ((int)(this["Multi_Copy_ID_13"]));
            }
            set {
                this["Multi_Copy_ID_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_14 {
            get {
                return ((int)(this["Multi_Copy_ID_14"]));
            }
            set {
                this["Multi_Copy_ID_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_15 {
            get {
                return ((int)(this["Multi_Copy_ID_15"]));
            }
            set {
                this["Multi_Copy_ID_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_16 {
            get {
                return ((int)(this["Multi_Copy_ID_16"]));
            }
            set {
                this["Multi_Copy_ID_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_17 {
            get {
                return ((int)(this["Multi_Copy_ID_17"]));
            }
            set {
                this["Multi_Copy_ID_17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_18 {
            get {
                return ((int)(this["Multi_Copy_ID_18"]));
            }
            set {
                this["Multi_Copy_ID_18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_19 {
            get {
                return ((int)(this["Multi_Copy_ID_19"]));
            }
            set {
                this["Multi_Copy_ID_19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_20 {
            get {
                return ((int)(this["Multi_Copy_ID_20"]));
            }
            set {
                this["Multi_Copy_ID_20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_21 {
            get {
                return ((int)(this["Multi_Copy_ID_21"]));
            }
            set {
                this["Multi_Copy_ID_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_22 {
            get {
                return ((int)(this["Multi_Copy_ID_22"]));
            }
            set {
                this["Multi_Copy_ID_22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_23 {
            get {
                return ((int)(this["Multi_Copy_ID_23"]));
            }
            set {
                this["Multi_Copy_ID_23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_24 {
            get {
                return ((int)(this["Multi_Copy_ID_24"]));
            }
            set {
                this["Multi_Copy_ID_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_25 {
            get {
                return ((int)(this["Multi_Copy_ID_25"]));
            }
            set {
                this["Multi_Copy_ID_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Multi_Copy_ID_26 {
            get {
                return ((int)(this["Multi_Copy_ID_26"]));
            }
            set {
                this["Multi_Copy_ID_26"] = value;
            }
        }
    }
}
