//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTSpecDB.Editor {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTSpecDB.Editor.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   \BACKUP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Index:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cm_TableIndex_Header {
            get {
                return ResourceManager.GetString("cm_TableIndex_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied cell &apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyCell_statusName1 {
            get {
                return ResourceManager.GetString("CopyCell_statusName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyCell_statusName2 {
            get {
                return ResourceManager.GetString("CopyCell_statusName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteRow_statusName {
            get {
                return ResourceManager.GetString("DeleteRow_statusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select file to export the table as TXT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportCurrentTable_dlg {
            get {
                return ResourceManager.GetString("ExportCurrentTable_dlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select file to export the table as CSV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportCurrentTableCSV_dlg {
            get {
                return ResourceManager.GetString("ExportCurrentTableCSV_dlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This ID is already being used by another row. Make sure you know what you are doing. Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_Duplicate_M {
            get {
                return ResourceManager.GetString("ID_Duplicate_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID in use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_Duplicate_T {
            get {
                return ResourceManager.GetString("ID_Duplicate_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The pasted row has an ID or Label that is already being used by another row. Make sure you know what you are doing. Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_or_Label_Duplicate_M {
            get {
                return ResourceManager.GetString("ID_or_Label_Duplicate_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID/Label in use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_or_Label_Duplicate_T {
            get {
                return ResourceManager.GetString("ID_or_Label_Duplicate_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This table is not entirely mapped - display errors &amp; missing data may be present. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsTableProperlyMapped_M {
            get {
                return ResourceManager.GetString("IsTableProperlyMapped_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table not mapped correctly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsTableProperlyMapped_T {
            get {
                return ResourceManager.GetString("IsTableProperlyMapped_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The label must contain only letters, numbers, or underscores. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_chara_error_M {
            get {
                return ResourceManager.GetString("Label_chara_error_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validation Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_chara_error_T {
            get {
                return ResourceManager.GetString("Label_chara_error_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Label is already being used by another row. Make sure you know what you are doing. Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Duplicate_M {
            get {
                return ResourceManager.GetString("Label_Duplicate_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Label in use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Duplicate_T {
            get {
                return ResourceManager.GetString("Label_Duplicate_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not load SpecDB:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Load_Failed_specDB_M {
            get {
                return ResourceManager.GetString("Load_Failed_specDB_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load the SpecDB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Load_Failed_specDB_T {
            get {
                return ResourceManager.GetString("Load_Failed_specDB_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not load table:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Load_Failed_Table_M {
            get {
                return ResourceManager.GetString("Load_Failed_Table_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table not loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Load_Failed_Table_T {
            get {
                return ResourceManager.GetString("Load_Failed_Table_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Loading_Table_statusName1 {
            get {
                return ResourceManager.GetString("Loading_Table_statusName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Loading_Table_statusName2 {
            get {
                return ResourceManager.GetString("Loading_Table_statusName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open SpecDB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Open_SpecDB {
            get {
                return ResourceManager.GetString("Open_SpecDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;Unsigned Byte&apos; type. It must be a number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_byte_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_byte_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;Float&apos; type. It must be a number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_float_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_float_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;Integer&apos; type. It must be number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_int_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_int_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;Long&apos; type. It must be a number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_long_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_long_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    and  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_M2 {
            get {
                return ResourceManager.GetString("Out_of_range_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_M3 {
            get {
                return ResourceManager.GetString("Out_of_range_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;Signed Byte&apos; type. It must be a number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_sbyte_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_sbyte_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;Short&apos; type. It must be number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_short_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_short_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validation Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_T {
            get {
                return ResourceManager.GetString("Out_of_range_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;Unsigned Integer&apos; type. It must be number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_uint_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_uint_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not parse &apos;UShort&apos; type. It must be number between  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Out_of_range_ushort_M1 {
            get {
                return ResourceManager.GetString("Out_of_range_ushort_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopulateTableColumns_Type {
            get {
                return ResourceManager.GetString("PopulateTableColumns_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save backup. Unable to write file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_Failed_Backup_M {
            get {
                return ResourceManager.GetString("Save_Failed_Backup_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_Failed_Backup_T {
            get {
                return ResourceManager.GetString("Save_Failed_Backup_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the CARS folder as GENERIC_CAR is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_Failed_CarsParts_M {
            get {
                return ResourceManager.GetString("Save_Failed_CarsParts_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table not loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_Failed_CarsParts_T {
            get {
                return ResourceManager.GetString("Save_Failed_CarsParts_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save PartsInfo as GENERIC_CAR is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_Failed_PartsInfo_M {
            get {
                return ResourceManager.GetString("Save_Failed_PartsInfo_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table not loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_Failed_PartsInfo_T {
            get {
                return ResourceManager.GetString("Save_Failed_PartsInfo_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder to save the CARS folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCarsParts_dlg {
            get {
                return ResourceManager.GetString("SaveCarsParts_dlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving Parts Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCarsParts_PW_Title {
            get {
                return ResourceManager.GetString("SaveCarsParts_PW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Car parts saved to  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCarsParts_statusName1 {
            get {
                return ResourceManager.GetString("SaveCarsParts_statusName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCarsParts_statusName2 {
            get {
                return ResourceManager.GetString("SaveCarsParts_statusName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder to save the table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCurrentTable_dlg {
            get {
                return ResourceManager.GetString("SaveCurrentTable_dlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table saved to  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCurrentTable_statusName1 {
            get {
                return ResourceManager.GetString("SaveCurrentTable_statusName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCurrentTable_statusName2 {
            get {
                return ResourceManager.GetString("SaveCurrentTable_statusName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder to save PartsInfo.tbd/tbi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavePartsInfo_dlg {
            get {
                return ResourceManager.GetString("SavePartsInfo_dlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving Parts Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavePartsInfo_PW_Title {
            get {
                return ResourceManager.GetString("SavePartsInfo_PW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PartsInfo.tbi/tbd saved to  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavePartsInfo_statusName1 {
            get {
                return ResourceManager.GetString("SavePartsInfo_statusName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavePartsInfo_statusName2 {
            get {
                return ResourceManager.GetString("SavePartsInfo_statusName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetNoProgress_statusName {
            get {
                return ResourceManager.GetString("SetNoProgress_statusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This string already exists in the string database. If you wish to select it search and select it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_already_exists_M {
            get {
                return ResourceManager.GetString("String_already_exists_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String already exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_already_exists_T {
            get {
                return ResourceManager.GetString("String_already_exists_T", resourceCulture);
            }
        }
    }
}
